# Debug mode switch
# Leave this set to `false`, unless you know what you're doing
debug = false

# Discord bot token
# ⚠️ Make sure this is kept secret!
token = ""

# Bot command prefix
command_prefix = "!"

# Bot administrator user IDs
# ⚠️ Specified users, as well as bot owners, will be granted full access to the bot!
administrators = []

# Enabled modules
modules = ["module_manager", "settings_manager"]
