# Debug mode switch
# Leave this set to `false`, unless you know what you're doing
debug = false

# Discord bot token
# ⚠️ Make sure this is kept secret!
token = ""

# List of bot command prefixes
command_prefixes = ["!"]

# Case insensitive prefix switch
case_insensitive_prefix = true

# Bot administrator user IDs
# ⚠️ Specified users, as well as bot owners, will be granted full access to the bot!
administrators = []

# Enabled modules
modules = ["oobe"]

openai_endpoint = "https://api.openai.com/v1"
openai_api_key = ""
model = "gpt-4o"
