# Debug mode switch
# Leave this set to `false`, unless you know what you're doing
debug = false

# Discord bot token
# ⚠️ Make sure this is kept secret!
token = ''

# Bot command prefix
command_prefix = '!'